# Generated by Django 6.1.1 on 2026-09-20 22:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('learning_goal', models.TextField(blank=True, null=True)),
                ('origin_reason', models.TextField(blank=True, null=True)),
                ('origin_file', models.FileField(blank=True, null=True, upload_to='media/files/reason')),
                ('status', models.CharField(choices=[('IDEA', 'Idea'), ('SOURCE_RESEARCH', 'Source Research'), ('LEARNING', 'Learning'), ('EXPERIENCE', 'Experience'), ('COMPLETED', 'Completed')], default='IDEA', max_length=30)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='project_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='TopicExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('difficulty_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('usefulness_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('interest_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('knowledge_before_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('knowledge_after_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('best_learning_method', models.CharField(blank=True, max_length=100, null=True)),
                ('final_summary', models.TextField(blank=True, null=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='project_app.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('RELATED', 'Related'), ('PREREQUISITE', 'Prerequisite'), ('NEXT_STEP', 'Next Step'), ('PART_OF', 'Part Of')], max_length=30)),
                ('related_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='project_app.topic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='project_app.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='media/files/sources/')),
                ('source_type', models.CharField(choices=[('BOOK', 'Book'), ('PAPER', 'Paper'), ('VIDEO', 'Video'), ('COURSE', 'Course'), ('ARTICLE', 'Article'), ('DOCUMENTATION', 'Documentation'), ('OTHER', 'Other')], max_length=30)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('quality_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('explanation_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('difficulty_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('usefulness_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('would_use_again_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='project_app.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_created', models.DateTimeField(blank=True, null=True)),
                ('source_research_start', models.DateTimeField(blank=True, null=True)),
                ('source_research_finish', models.DateTimeField(blank=True, null=True)),
                ('learning_start', models.DateTimeField(blank=True, null=True)),
                ('learning_finish', models.DateTimeField(blank=True, null=True)),
                ('experience_start', models.DateTimeField(blank=True, null=True)),
                ('experience_finish', models.DateTimeField(blank=True, null=True)),
                ('topic_finish', models.DateTimeField(blank=True, null=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='project_app.topic')),
            ],
        ),
    ]
