# Generated by Django 6.1.1 on 2026-09-20 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topics',
        ),
        migrations.AlterModelTable(
            name='topicexperience',
            table='topic_experiences',
        ),
        migrations.AlterModelTable(
            name='topicrelation',
            table='topic_relations',
        ),
        migrations.AlterModelTable(
            name='topicsource',
            table='topic_sources',
        ),
        migrations.AlterModelTable(
            name='topictimeline',
            table='topic_timelines',
        ),
    ]
